"""Fetch relevant PubMed papers and add Claude relevance summaries."""

import json
import logging
import os
import re
import xml.etree.ElementTree as ET
from urllib.parse import quote_plus
from urllib.request import urlopen
from urllib.error import URLError

PUBMED_BASE = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"
_TOOL  = "greenlit-ai-gras"
_EMAIL = os.environ.get("PUBMED_EMAIL", "gras-tool@greenlit.ai")
_TIMEOUT = 12  # seconds per request


_HEADERS = {
    "User-Agent": f"greenlit-ai-gras/1.0 (mailto:{_EMAIL})",
    "Accept": "application/json, text/xml, */*",
}

def _get(url: str) -> bytes:
    from urllib.request import Request
    req = Request(url, headers=_HEADERS)
    try:
        with urlopen(req, timeout=_TIMEOUT) as r:
            return r.read()
    except Exception as e:
        raise RuntimeError(f"PubMed request failed: {e}") from e


def _build_query(substance: str, method: str, organism: str) -> str:
    # Strip parenthetical organism suffixes, e.g. "Brazzein (K. phaffii)" â†’ "Brazzein"
    clean = re.sub(r'\s*\(.*?\)', '', substance).strip()
    safety_terms = '("food safety" OR "GRAS" OR "safety assessment" OR toxicology OR "dietary exposure")'
    parts = [f'{clean}[Title/Abstract]', safety_terms]
    if organism and organism.lower() not in clean.lower():
        parts.append(f'{organism}[Title/Abstract]')
    return " AND ".join(parts)


def _esearch(query: str, retmax: int = 8) -> list[str]:
    url = (
        f"{PUBMED_BASE}/esearch.fcgi"
        f"?db=pubmed&term={quote_plus(query)}&retmax={retmax}"
        f"&sort=relevance&retmode=json&tool={_TOOL}&email={_EMAIL}"
    )
    data = json.loads(_get(url))
    return data["esearchresult"]["idlist"]


def _esummary(pmids: list[str]) -> dict:
    url = (
        f"{PUBMED_BASE}/esummary.fcgi"
        f"?db=pubmed&id={','.join(pmids)}&retmode=json&tool={_TOOL}&email={_EMAIL}"
    )
    return json.loads(_get(url))["result"]


def _efetch_abstracts(pmids: list[str]) -> dict[str, str]:
    url = (
        f"{PUBMED_BASE}/efetch.fcgi"
        f"?db=pubmed&id={','.join(pmids)}&rettype=abstract&retmode=xml"
        f"&tool={_TOOL}&email={_EMAIL}"
    )
    root = ET.fromstring(_get(url))
    out: dict[str, str] = {}
    for article in root.findall(".//PubmedArticle"):
        pmid_el = article.find(".//PMID")
        abstract_el = article.find(".//AbstractText")
        if pmid_el is not None and abstract_el is not None:
            text = "".join(abstract_el.itertext()).strip()
            out[pmid_el.text] = text[:2_000]
    return out


def _claude_summaries(papers: list[dict], substance: str) -> list[dict]:
    """One-sentence relevance note per paper, generated by Claude Haiku."""
    import anthropic
    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

    block = "\n\n".join(
        f"[{i+1}] {p['title']}\nAbstract: {p.get('abstract', '')[:600] or 'Not available.'}"
        for i, p in enumerate(papers)
    )
    prompt = (
        f"You are reviewing scientific literature for a GRAS safety assessment of {substance}.\n\n"
        "For each paper below write ONE sentence (max 20 words) explaining its specific "
        "relevance to a GRAS safety filing. Be concrete — name the data type, species, or "
        "finding that matters.\n\n"
        f"{block}\n\n"
        'Reply with a JSON array of strings, one per paper, same order. '
        'Example: ["Establishes precedent for fermentation-derived protein safety at similar exposure.", ...]'
    )
    response = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=512,
        messages=[{"role": "user", "content": prompt}],
    )
    text = response.content[0].text.strip()
    match = re.search(r"\[.*?\]", text, re.DOTALL)
    if match:
        try:
            summaries = json.loads(match.group())
            for i, p in enumerate(papers):
                if i < len(summaries):
                    p["relevance"] = summaries[i]
        except Exception:
            logging.warning("Failed to parse Claude relevance summaries")
    return papers


def fetch_research(substance: str, method: str = "", organism: str = "") -> list[dict]:
    """Return up to 3 relevant PubMed papers with metadata and relevance summaries."""
    clean = re.sub(r'\s*\(.*?\)', '', substance).strip()
    query = _build_query(substance, method, organism)
    logging.info("PubMed query: %r", query)

    pmids = _esearch(query, retmax=10)
    if len(pmids) < 3:
        # Broaden: drop organism constraint, keep safety terms
        fallback1 = f'{clean}[Title/Abstract] AND ("food safety" OR GRAS OR toxicology OR "safety assessment")'
        extra = _esearch(fallback1, retmax=10)
        pmids = list(dict.fromkeys(pmids + extra))  # deduplicate, preserve order
    if len(pmids) < 3:
        # Even broader: just substance name + food anywhere
        extra2 = _esearch(f'{clean} AND food', retmax=10)
        pmids = list(dict.fromkeys(pmids + extra2))
    if not pmids:
        return []

    summary_data = _esummary(pmids)
    abstracts    = _efetch_abstracts(pmids)

    papers: list[dict] = []
    for pmid in pmids:
        if pmid not in summary_data or pmid == "uids":
            continue
        s = summary_data[pmid]

        doi = next(
            (a["value"] for a in s.get("articleids", []) if a.get("idtype") == "doi"),
            None,
        )
        authors = s.get("authors", [])
        author_str = ""
        if authors:
            first = authors[0].get("name", "")
            author_str = f"{first} et al." if len(authors) > 1 else first

        papers.append({
            "pmid":    pmid,
            "title":   s.get("title", "").rstrip("."),
            "authors": author_str,
            "journal": s.get("fulljournalname") or s.get("source", ""),
            "year":    s.get("pubdate", "")[:4],
            "doi":     doi,
            "url":     f"https://pubmed.ncbi.nlm.nih.gov/{pmid}/",
            "abstract": abstracts.get(pmid, ""),
        })
        if len(papers) >= 3:
            break

    if papers:
        try:
            papers = _claude_summaries(papers, substance)
        except Exception:
            logging.warning("Claude relevance summaries unavailable", exc_info=True)

    return papers
