export const MOCK_RESULT = {
  engagement_summary: {
    substance_name: 'Brazzein (Komagataella phaffii)',
    notifier: 'Acme Biotech Inc.',
    date_filed: '2024-09-15',
    gras_basis: 'scientific_procedures',
    substance_type: 'enzyme',
    intended_uses: ['general purpose sweetener', 'beverages', 'foods'],
    production_method: 'Precision fermentation in yeast expression system',
    source_organism: 'Komagataella phaffii',
    source_organism_name: 'Komagataella phaffii',
    target_population: 'General population',
    dietary_exposure_method: 'USDA food consumption database',
  },
  gap_report: {
    score: 38,
    priority_counts: { foundational: 2, material: 3, documentation_issue: 4 },
  },
  gap_field_presence: {
    dietary_exposure_estimate: false,
    allergenicity_assessment: true,
    genotoxicity_battery: false,
    digestibility_data: true,
    nutritional_impact: true,
    human_exposure_data: false,
    history_of_safe_use: false,
  },
  consolidated_gap_summary: [
    {
      priority: 'foundational',
      title: 'No dietary exposure estimate provided',
      domain: 'dietary_exposure',
      observation: 'Part 5 contains no quantitative estimate of dietary exposure. Without a mg/kg bw/day figure tied to a recognized consumption model (NHANES, USDA), the FDA cannot assess whether the safety margin is adequate.',
      section_reference: 'Part 5, Â§5.2',
      approved_reference: { grn_number: 412, substance_name: 'Lacticaseibacillus rhamnosus GG', section_label: 'Part 5 â€” Dietary Exposure' },
    },
    {
      priority: 'foundational',
      title: 'Genotoxicity battery incomplete',
      domain: 'toxicology',
      observation: 'Only an Ames test is reported. A complete battery requires both a gene mutation assay and a chromosomal aberration/micronucleus assay per ICH S2(R1) guidance.',
      section_reference: 'Part 6, Â§6.3',
      approved_reference: { grn_number: 894, substance_name: 'Ovalbumin (precision fermentation)', section_label: 'Part 6 â€” Genotoxicity' },
    },
    {
      priority: 'material',
      title: 'Allergenicity assessment method not described',
      domain: 'allergenicity',
      observation: 'The notice states the substance was evaluated for allergenicity but does not describe the bioinformatics pipeline, sequence homology threshold, or databases queried.',
      section_reference: 'Part 6, Â§6.1',
      approved_reference: null,
    },
    {
      priority: 'material',
      title: 'Human exposure data absent',
      domain: 'dietary_exposure',
      observation: 'No human clinical trial or epidemiological data is cited. While not required, its absence weakens the overall weight of evidence argument for a novel protein.',
      section_reference: 'Part 6, Â§6.5',
      approved_reference: { grn_number: 756, substance_name: 'Beta-lactoglobulin (fermentation)', section_label: 'Part 6 â€” Human Data' },
    },
    {
      priority: 'material',
      title: 'Expert panel composition undisclosed',
      domain: 'gras_panel',
      observation: 'The GRAS panel section lists credentials in general terms but does not name individual panelists or disclose conflicts of interest, inconsistent with FDA expectations.',
      section_reference: 'Part 4, Â§4.1',
      approved_reference: null,
    },
    {
      priority: 'documentation_issue',
      title: 'Intended use population not specified',
      domain: 'intended_use',
      observation: 'The notice describes intended use broadly as "foods and beverages" without specifying whether vulnerable populations (infants, pregnant women) are excluded.',
      section_reference: 'Part 3, Â§3.1',
      approved_reference: null,
    },
    {
      priority: 'documentation_issue',
      title: 'Batch-to-batch variability data missing',
      domain: 'manufacturing',
      observation: 'Characterization data is provided for a single lot. Multiple-lot data is expected to demonstrate manufacturing consistency.',
      section_reference: 'Part 2, Â§2.4',
      approved_reference: null,
    },
    {
      priority: 'documentation_issue',
      title: 'Literature search date not reported',
      domain: 'literature',
      observation: 'The literature review does not state the search cutoff date, making it impossible to verify currency.',
      section_reference: 'Part 6, Â§6.0',
      approved_reference: null,
    },
    {
      priority: 'documentation_issue',
      title: 'Regulatory history incomplete',
      domain: 'regulatory',
      observation: 'International regulatory status (EFSA, Health Canada) is not addressed, which is increasingly expected for novel fermentation-derived ingredients.',
      section_reference: 'Part 1, Â§1.3',
      approved_reference: null,
    },
  ],
  potential_safety_signals: [
    {
      signal: 'Production strain antibiotic resistance genes present',
      evidence: 'Appendix B genome annotation lists kanamycin resistance cassette in the expression vector. This has triggered FDA questions in two recent precision fermentation GRNs.',
      section_reference: 'Appendix B, Table B-3',
      recommended_action: 'Provide evidence that the resistance gene is not transferred to the fermentation product and cannot mobilize into gut flora. Reference EFSA 2018 guidance on marker genes.',
    },
    {
      signal: 'Subchronic toxicology study conducted at single dose level',
      evidence: 'The 90-day rat study used only the high dose (1000 mg/kg bw/day). OECD 408 requires at least three dose levels plus control to establish a NOAEL.',
      section_reference: 'Part 6, Â§6.4, Table 6-2',
      recommended_action: 'Commission a repeat study at three dose levels or provide scientific justification for the single-dose design with reference to FDA/OECD precedent.',
    },
  ],
  recommended_next_steps: [
    {
      gap_title: 'No dietary exposure estimate provided',
      domain: 'dietary_exposure',
      fda_pushback_probability: 'high',
      pushback_reasoning: 'FDA has issued questions on every precision fermentation GRN lacking a quantitative exposure estimate since 2021.',
      action: 'Develop a probabilistic exposure estimate using NHANES 2017-2020 data and the anticipated use levels. Apply the Tier 2 MSDI approach for initial screening.',
      withdrawn_reference: null,
    },
    {
      gap_title: 'Genotoxicity battery incomplete',
      domain: 'toxicology',
      fda_pushback_probability: 'high',
      pushback_reasoning: 'A complete two-assay battery is a de facto requirement for novel food ingredients. Single Ames tests have been explicitly flagged in prior FDA correspondence.',
      action: 'Commission a GLP-compliant in vitro micronucleus (MNvit) assay per OECD 487. Results should be available within 8-12 weeks from a qualified CRO.',
      withdrawn_reference: { grn_number: 623, substance_name: 'Lactoferrin (fermentation-derived)' },
    },
    {
      gap_title: 'Allergenicity assessment method not described',
      domain: 'allergenicity',
      fda_pushback_probability: 'medium',
      pushback_reasoning: 'FDA reviewers consistently ask for the bioinformatics pipeline specifics when the source organism is non-traditional.',
      action: 'Supplement the notice with a detailed allergenicity assessment appendix: database versions, e-value threshold, FAO/WHO 8-mer sliding window analysis, and IgE binding results.',
      withdrawn_reference: null,
    },
    {
      gap_title: 'Expert panel composition undisclosed',
      domain: 'gras_panel',
      fda_pushback_probability: 'medium',
      pushback_reasoning: 'Anonymous panels have been questioned in recent GRNs. FDA expects panelist CVs and conflict-of-interest disclosures.',
      action: 'Amend Part 4 to include named panelists with abbreviated CVs and signed conflict-of-interest statements. This is administrative and can be completed quickly.',
      withdrawn_reference: null,
    },
    {
      gap_title: 'Regulatory history incomplete',
      domain: 'regulatory',
      fda_pushback_probability: 'low',
      pushback_reasoning: 'Unlikely to be a blocking issue but demonstrates regulatory rigor when included.',
      action: 'Add a one-page regulatory status summary covering EU Novel Food status, Health Canada, and any FSANZ or CODEX Alimentarius positions.',
      withdrawn_reference: null,
    },
  ],
  benchmark: {
    applicable_fields: {
      dietary_exposure_estimate: true,
      allergenicity_assessment: true,
      genotoxicity_battery: true,
      digestibility_data: true,
      nutritional_impact: true,
      human_exposure_data: true,
      history_of_safe_use: false,
    },
    proxy_score: { current: 0.61, approved_mean: 0.18 },
    corpus_baseline: {
      fields: {
        dietary_exposure_estimate: { rate: 0.91 },
        allergenicity_assessment:  { rate: 0.97 },
        genotoxicity_battery:      { rate: 0.84 },
        digestibility_data:        { rate: 0.72 },
        nutritional_impact:        { rate: 0.68 },
        human_exposure_data:       { rate: 0.41 },
        history_of_safe_use:       { rate: 0.55 },
      },
    },
  },
  comparative_analysis: {
    approved_notices: [
      {
        grn_number: 894, substance_name: 'Ovalbumin (precision fermentation)', notifier: 'Onego Bio Ltd.',
        status: 'no_questions', date_filed: '2023-11-01', production_method: 'precision_fermentation',
        best_distance: 0.12,
        exposure_estimate_included: true, allergenicity_addressed: true,
        safety_data_available: 'genotoxicity_ames, genotoxicity_chromosomal, digestibility_study, nutritional_impact',
      },
      {
        grn_number: 756, substance_name: 'Beta-lactoglobulin (fermentation)', notifier: 'TurtleTree Labs',
        status: 'no_questions', date_filed: '2022-06-14', production_method: 'precision_fermentation',
        best_distance: 0.19,
        exposure_estimate_included: true, allergenicity_addressed: true,
        safety_data_available: 'genotoxicity_ames, digestibility_study, human_clinical_trial',
      },
    ],
    withdrawn_notices: [
      {
        grn_number: 623, substance_name: 'Lactoferrin (fermentation-derived)', notifier: 'Synlogic Inc.',
        status: 'withdrawn', date_filed: '2021-03-22', production_method: 'precision_fermentation',
        best_distance: 0.27,
        exposure_estimate_included: false, allergenicity_addressed: true,
        safety_data_available: 'genotoxicity_ames, digestibility_study',
      },
    ],
  },
  limitations_and_caveats: 'This analysis is AI-generated and should be reviewed by a qualified regulatory professional before use. Gap identification is based on pattern matching against ~950 historical GRAS notices and may not capture all FDA-specific expectations for this particular substance class. Safety signals are flagged for human review and do not constitute a legal or scientific determination.',
  meta: { truncated: false, skipped_pages: 0 },
}
